on:
  push:
    branches:
      - master

name: Deploy in here

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        aws-access-key-id: my-name
        aws-secret-access-key: my-Name2
        AWS_REGION: us-east-1

    steps:
    - name: Checkout
      id: checkout
      run: 
        echo "name=$AWS_REGION"
    
    - name: Configure AWS credentials
      run: 
        echo "name=$AWS_REGION"
