on:
  push:
    branches:
      - master

name: Deploy in here

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      env:
        aws-access-key-id: my-name
        aws-secret-access-key: my-Name2
        AWS_REGION: us-east-1
      run: 
        echo "::set-output name=image::$AWS_REGION"
    
    - name: Configure AWS credentials
      run: 
        echo "::set-output name=image::${{steps.checkout.env.AWS_REGION}}"
