on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      with:
        aws-access-key-id: my-name
        aws-secret-access-key: my-Name2
        aws-region: us-east-1
    
    - name: Configure AWS credentials
      run: 
        echo "::set-output name=image::${{steps.checkout.env.aws-region}}
